execute pathogen#infect()
set nocompatible
set relativenumber
set number
set cursorline
syntax on
filetype plugin indent on
if has("gui_macvim")
    set guifont=Menlo\ Regular:h12 
endif
set background=dark
if has("gui")
    let g:solarized_menu=0
endif 
colorscheme solarized
set expandtab
set shiftwidth=4
set softtabstop=4
