set nocompatible
let s:root = fnamemodify(resolve(expand('<sfile>:p')), ':h')
execute pathogen#infect(s:root . "/bundle/{}")
if has("mac")
    execute pathogen#infect(s:root . "/mac_bundle/{}")
endif
set relativenumber
set number
set cursorline
syntax on
filetype plugin indent on
if has("gui_macvim")
    set guifont=Menlo\ Regular:h12 
endif
set background=dark
if has("gui")
    let g:solarized_menu=0
endif 
if hostname() ==# "Lexx.local"
    let g:solarized_termcolors=256
endif
colorscheme solarized
set expandtab
set shiftwidth=4
set softtabstop=4
