set nocompatible
if &shell =~# 'fish$'
    set shell=bash
endif
let s:root = fnamemodify(resolve(expand('<sfile>:p')), ':h')
execute pathogen#infect(s:root . "/{}", s:root . "/bundle/{}")
if has("mac")
    execute pathogen#infect(s:root . "/mac_bundle/{}")
endif
set relativenumber
set number
set cursorline
syntax on
filetype plugin indent on
if has("gui_macvim")
    set guifont=Menlo\ Regular:h16 
endif
set background=light
colorscheme Atelier_SeasideDark
" colorscheme Atelier_PlateauDark
" colorscheme Atelier_SulphurpoolDark
set expandtab
set shiftwidth=2
set softtabstop=2
" TODO move into a bundle
autocmd FileType go let g:go_autodetect_gopath = 0
autocmd FileType go set expandtab&
autocmd FileType go set softtabstop&
autocmd FileType go set tabstop=4
" TODO move into a bundle
autocmd FileType ruby compiler ruby
